### ISSUE TITLE
Neovim freezes when the nvim-hs plugin throws a runtime error

### ISSUE THREAD

**Issue by koslambrou** [neovimhaskell/nvim-hs#48]
I tried testing the Fibonacci example plugin provided by nvim-hs.

However, when I change the plugin code to something which generates an error, Neovim freezes with no shown error.

For example, the following code would work for `:echo fibonacci(0)`, but the freeze would occur in `:echo fibonacci(1)`.

```
fibonacci :: Int -> Neovim' String
fibonacci n = return . show $ fibs !! n
  where fibs = [0]
```

Is that normal?

**Comment by saep** [comment]
No, it shouldn't freeze. 
I hope I have a fix for this this in a few hours.

**Comment by saep** [comment]
This problem is rather annoying to fix. It is essentially pure code that throws the exception, so the answer of [this stackoverflow post](http://stackoverflow.com/questions/4243117/how-to-catch-and-ignore-a-call-to-the-error-function) fits this problem.

I can make a short and reliable fix to this problem if the underlying messagepack library adds an NFData instance to its objects.

A frozen neovim might be a good incentive not to use partial functions, though. :-)

**Comment by koslambrou** [comment]
Alright! Thanks for the info and the heads up. :)

**Comment by saep** [comment]
Can't make the test work on travis, but it's fixed in master. I might do a release soon.
